// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchLyrics(arg1:string):Promise<Array<main.LyricLine>>;

export function FetchMusicInfo():Promise<main.MusicInfo>;

export function FetchPlayerState():Promise<main.PlayerState>;

export function GetConfig():Promise<main.AppConfig>;

export function Next():Promise<void>;

export function PlayPause():Promise<void>;

export function Previous():Promise<void>;

export function QuitApp():Promise<void>;

export function ResizeWindow(arg1:number,arg2:number):Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SetWindowClickThrough(arg1:boolean,arg2:main.DOMRect):Promise<void>;
