// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchLyrics(arg1) {
  return window['go']['main']['App']['FetchLyrics'](arg1);
}

export function FetchMusicInfo() {
  return window['go']['main']['App']['FetchMusicInfo']();
}

export function FetchPlayerState() {
  return window['go']['main']['App']['FetchPlayerState']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function Next() {
  return window['go']['main']['App']['Next']();
}

export function PlayPause() {
  return window['go']['main']['App']['PlayPause']();
}

export function Previous() {
  return window['go']['main']['App']['Previous']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ResizeWindow(arg1, arg2) {
  return window['go']['main']['App']['ResizeWindow'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetWindowClickThrough(arg1, arg2) {
  return window['go']['main']['App']['SetWindowClickThrough'](arg1, arg2);
}
